<h1>Faça seu Login</h1>



<?php
$username = $form->get('username');
$username->setAttribute('class','form-control');
$username->setLabelAttributes(['class' => 'control-label']);

$password = $form->get('password');
$password->setAttribute('class','form-control');
$password->setLabelAttributes(['class' => 'control-label']);

$submit = $form->get('submit');
$submit->setAttribute('class','btn btn-primary');

$form->setAttribute('action', $this->url('login'));
#php -r "echo password_hash('123456', PASSWORD_BCRYPT);"
$form->prepare();
?>

<?php if ($messageError): ?>
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span>
        </button>
        <strong>Erro!</strong> <?= $messageError; ?>
    </div>
<?php endif; ?>

<?php if ($messageLogout): ?>
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span>
        </button>
        <strong>Sucesso!</strong> <?= $messageLogout; ?>
    </div>
<?php endif; ?>


<div class="row" >
    <div class="col-md-6" >

        <? echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?=$this->formLabel($username);?>
            <?=$this->formElement($username);?>
        </div>

        <div class="form-group">
            <?=$this->formLabel($password);?>
            <?=$this->formElement($password);?>
        </div>

        <?php
        echo $this->formSubmit($submit);

        echo $this->form()->closeTag();
        ?>

    </div>
</div>