<?php
// module/blog/view/blog/blog/index.phtml:

$title = 'Meus Blogs';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('admin-blog/blog', ['action' => 'add']) ?>">Add new blog</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Content</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($blogs as $blog) : ?>
    <tr>
        <td><?= $this->escapeHtml($blog->title) ?></td>
        <td><?= $this->escapeHtml($blog->content) ?></td>
        <td>
            <a href="<?= $this->url('admin-blog/blog', ['action' => 'edit', 'id' => $blog->id]) ?>">Edit</a>
            <a href="<?= $this->url('admin-blog/blog', ['action' => 'delete', 'id' => $blog->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>

